media: media

content:
  - name: pages
    label: Pages
    type: collection
    path: content/pages
    fields:
      - name: title
        label: Titre
        type: string

      - name: body
        label: Contenu
        type: rich-text